# Generated by Django 5.0.6 on 2024-05-23 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_name_alter_user_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='user',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='referrer_name',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='reward',
        ),
        migrations.AddField(
            model_name='referral',
            name='referrer',
            field=models.ForeignKey(default='10', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='referral',
            name='referred_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='referral',
            name='unique_code',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
