# Generated by Django 5.0.6 on 2024-05-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_referral_user_remove_referral_referrer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='reward',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
